-- 테이블 생성
CREATE TABLE TB_ADMIN_ANSWERS (
    ANSWER_ID      NUMBER(18)      DEFAULT SEQ_ANSWER_ID.NEXTVAL NOT NULL, -- 답변 ID
    PETITION_ID    NUMBER(18)      NOT NULL, -- 청원 ID
    USER_ID        VARCHAR2(50)    NOT NULL, -- 관리자 ID
    CONTENT        CLOB            NULL,     -- 답변 내용
    CREATED_DATE   DATE            DEFAULT SYSDATE NOT NULL, -- 답변일
    CONSTRAINT PK_TB_ADMIN_ANSWERS PRIMARY KEY (ANSWER_ID)
);

-- 시퀀스 생성
CREATE SEQUENCE SEQ_ANSWER_ID
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9999999999
    NOCYCLE
    NOCACHE;
    
commit;

ALTER TABLE TB_ADMIN_ANSWERS
ADD CONSTRAINT FK_TB_ADMIN_ANSWERS_PETITION_ID
FOREIGN KEY (PETITION_ID)
REFERENCES TB_PETITIONS (PETITION_ID)
ON DELETE CASCADE;
