CREATE TABLE TB_PETITION_REPORTS (
    REPORT_ID NUMBER(18) DEFAULT SEQ_REPORT_ID.nextval, -- 신고 ID
    PETITION_ID NUMBER(18) NOT NULL, -- 청원 ID
    COMMENT_ID NUMBER(18),
    USER_ID VARCHAR2(50) NOT NULL, -- 사용자 ID
    REPORT_REASON CLOB, -- 신고 사유
    REPORTED_DATE DATE DEFAULT SYSDATE NOT NULL, -- 신고일
    CONSTRAINT PK_REPORTS PRIMARY KEY (REPORT_ID),
    CONSTRAINT FK_PETITION FOREIGN KEY (PETITION_ID) REFERENCES TB_PETITIONS(PETITION_ID),
    CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES TB_USERS(USER_ID)
);

create sequence seq_report_id NOCACHE NOCYCLE;

drop table TB_PETITION_REPORTS;

select REPORT_ID as reportId, PETITION_ID as petitionId, USER_ID as userId, REPORT_REASON as content, REPORTED_DATE as createDate
  from TB_PETITION_REPORTS;
  
ALTER TABLE TB_PETITION_REPORTS 
ADD CONSTRAINT FK_PETITION FOREIGN KEY (PETITION_ID)
REFERENCES TB_PETITIONS(PETITION_ID)
ON DELETE CASCADE;

ALTER TABLE TB_PETITION_REPORTS 
ADD CONSTRAINT FK_USER FOREIGN KEY (USER_ID)
REFERENCES TB_USERS(USER_ID)
ON DELETE CASCADE;

select * 
  from TB_PETITION_REPORTS;

SELECT REPORT_ID as reportId, PETITION_ID as petitionId, USER_ID as userId, REPORT_REASON as content, REPORTED_DATE as createDate
         FROM TB_PETITION_REPORTS
        ORDER BY REPORTED_DATE DESC
        OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY;