--  TB_PETITION_PARTICIPANTS                
CREATE TABLE TB_PETITION_PARTICIPANTS (
    PETITION_ID NUMBER(18) NOT NULL,                  -- 청원 ID
    USER_ID VARCHAR2(50) NOT NULL,                   -- 사용자 ID
    JOINED_DATE DATE DEFAULT SYSDATE NOT NULL,         -- 참여일 (기본값: SYSDATE)
    CONSTRAINT PK_TB_PETITION_PARTICIPANTS PRIMARY KEY (PETITION_ID, USER_ID), -- 복합 기본키 설정
    CONSTRAINT FK_TB_PETITION_PARTICIPANTS_PETITION_ID FOREIGN KEY (PETITION_ID) -- 외래키 (TB_PETITIONS)
        REFERENCES TB_PETITIONS (PETITION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_TB_PETITION_PARTICIPANTS_USER_ID FOREIGN KEY (USER_ID) -- 외래키 (TB_USER)
        REFERENCES TB_USERS (USER_ID) ON DELETE CASCADE
);

commit;
 

drop table TB_PETITION_PARTICIPANTS;

SELECT *
  FROM TB_PETITION_PARTICIPANTS;
  
  
SELECT COUNT(1)
  FROM TB_PETITION_PARTICIPANTS
 WHERE PETITION_ID = 24;
 
SELECT M1.PETITION_ID AS petitionId,
		TITLE,
		CONTENT,
		CATEGORY,
		CLOSE_DATE AS
		closeDate,
		PETITION_STATUS AS status,
		M2.JOINED_DATE AS createdDate,
		M1.USER_ID
		FROM TB_PETITIONS M1
		     JOIN TB_PETITION_PARTICIPANTS M2 ON M2.PETITION_ID = M1.PETITION_ID
        WHERE M2.USER_ID = 'qwer';
        
SELECT
		M1.PETITION_ID AS petitionId,
		M1.TITLE,
		M1.CATEGORY,
		M1.PETITION_STATUS as status,
		M1.CLOSE_DATE AS closeDate,
		COUNT(M2.USER_ID) as participantCount
		FROM TB_PETITIONS M1
		LEFT JOIN TB_PETITION_PARTICIPANTS M2
		ON M1.PETITION_ID = M2.PETITION_ID
		GROUP BY M1.PETITION_ID, M1.TITLE, M1.CATEGORY, M1.PETITION_STATUS, M1.CLOSE_DATE
		ORDER BY M1.CLOSE_DATE DESC
		OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY
        
        
